---
- name: Install nginx
  hosts: servers
  become: yes

  tasks:
    - name: Ensures that nginx is installed
      apt:
        name: nginx
        state: present

    - name: Ensures that apache is not installed
      apt:
        name: apache2
        state: absent

    - name: Ensures that nginx is running
      systemd_service:
        name: nginx
        state: started
